[
  {
    "domain": ".instagram.com",
    "expirationDate": 1779810387.364763,
    "hostOnly": false,
    "httpOnly": true,
    "name": "ps_n",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": null,
    "value": "1"
  },
  {
    "domain": ".instagram.com",
    "expirationDate": 1775886082.728409,
    "hostOnly": false,
    "httpOnly": true,
    "name": "datr",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": null,
    "value": "ApHsaCUoYBUxdWgi1xrqrSiD"
  },
  {
    "domain": ".instagram.com",
    "expirationDate": 1775886084.08728,
    "hostOnly": false,
    "httpOnly": false,
    "name": "ig_nrcb",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": null,
    "value": "1"
  },
  {
    "domain": ".instagram.com",
    "expirationDate": 1779877440.946427,
    "hostOnly": false,
    "httpOnly": false,
    "name": "ds_user_id",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": null,
    "value": "6659815781"
  },
  {
    "domain": ".instagram.com",
    "expirationDate": 1787653440.946295,
    "hostOnly": false,
    "httpOnly": false,
    "name": "csrftoken",
    "path": "/",
    "sameSite": null,
    "secure": true,
    "session": false,
    "storeId": null,
    "value": "YgEe11ts9gQAAh3Ov8zhYDvF2gBREZVg"
  },
  {
    "domain": ".instagram.com",
    "expirationDate": 1775886088.527359,
    "hostOnly": false,
    "httpOnly": true,
    "name": "ig_did",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": null,
    "value": "398F21BC-BBAC-4A74-8FA5-E29EEE24210D"
  },
  {
    "domain": ".instagram.com",
    "expirationDate": 1779810387.364564,
    "hostOnly": false,
    "httpOnly": true,
    "name": "ps_l",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": false,
    "storeId": null,
    "value": "1"
  },
  {
    "domain": ".instagram.com",
    "expirationDate": 1772706236,
    "hostOnly": false,
    "httpOnly": false,
    "name": "wd",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": false,
    "storeId": null,
    "value": "1920x967"
  },
  {
    "domain": ".instagram.com",
    "expirationDate": 1775886084.086934,
    "hostOnly": false,
    "httpOnly": false,
    "name": "mid",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": null,
    "value": "aOyRAwAEAAHAg9gXNSCzS4IA_oZr"
  },
  {
    "domain": ".instagram.com",
    "expirationDate": 1787653439.559661,
    "hostOnly": false,
    "httpOnly": true,
    "name": "sessionid",
    "path": "/",
    "sameSite": null,
    "secure": true,
    "session": false,
    "storeId": null,
    "value": "6659815781%3Am1B93JaAtUDAi5%3A12%3AAYjRfd780HzBvkAPVfBTyXCaNHDVNopewRX6MQCFSg"
  },
  {
    "domain": ".instagram.com",
    "hostOnly": false,
    "httpOnly": true,
    "name": "rur",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": true,
    "storeId": null,
    "value": "\"HIL\\0546659815781\\0541803637440:01fedd4747df247c91cdd57fbbc6fecb5935b3cb9a27bb75a6627f6dbc9dd8ef112514ff\""
  }
]
